insert into furniture (brand_id,category_id,furniture_name,real_height,real_width,pixel_height,pixel_width,resolution,click_rate,file_path,file_name)
VALUES (3,null,'accent_f_30x30_mirror',30,30,120,120,72,0,'./public/app/Media/furniture_objects/','accent_f_30x30_mirror.png')
insert into furniture (brand_id,category_id,furniture_name,real_height,real_width,pixel_height,pixel_width,resolution,click_rate,file_path,file_name)
VALUES (3,null,'accent_f_44x44_mirror',44,44,176,176,72,0,'./public/app/Media/furniture_objects/','accent_f_44x44_mirror.png')
insert into furniture (brand_id,category_id,furniture_name,real_height,real_width,pixel_height,pixel_width,resolution,click_rate,file_path,file_name)
VALUES (3,null,'bed_f_35x64_mikkel',35,64,140,256,72,0,'./public/app/Media/furniture_objects/','bed_f_35x64_mikkel.png')
insert into furniture (brand_id,category_id,furniture_name,real_height,real_width,pixel_height,pixel_width,resolution,click_rate,file_path,file_name)
VALUES (3,null,'bed_f_51x65_chloe',51,65,204,260,72,0,'./public/app/Media/furniture_objects/','bed_f_51x65_chloe.png')
insert into furniture (brand_id,category_id,furniture_name,real_height,real_width,pixel_height,pixel_width,resolution,click_rate,file_path,file_name)
VALUES (3,null,'bed_r_35x91_mikkel',35,91,140,364,72,0,'./public/app/Media/furniture_objects/','bed_r_35x91_mikkel.png')
insert into furniture (brand_id,category_id,furniture_name,real_height,real_width,pixel_height,pixel_width,resolution,click_rate,file_path,file_name)
VALUES (3,null,'bed_r_51x93_chloe',51,93,204,372,72,0,'./public/app/Media/furniture_objects/','bed_r_51x93_chloe.png')
insert into furniture (brand_id,category_id,furniture_name,real_height,real_width,pixel_height,pixel_width,resolution,click_rate,file_path,file_name)
VALUES (3,null,'bed_s_35x91_mikkel',35,91,140,364,72,0,'./public/app/Media/furniture_objects/','bed_s_35x91_mikkel.png')
insert into furniture (brand_id,category_id,furniture_name,real_height,real_width,pixel_height,pixel_width,resolution,click_rate,file_path,file_name)
VALUES (3,null,'bed_s_51x93_chloe',51,93,204,372,72,0,'./public/app/Media/furniture_objects/','bed_s_51x93_chloe.png')
insert into furniture (brand_id,category_id,furniture_name,real_height,real_width,pixel_height,pixel_width,resolution,click_rate,file_path,file_name)
VALUES (3,null,'bench_f_22x69_ziggy',22,69,88,276,72,0,'./public/app/Media/furniture_objects/','bench_f_22x69_ziggy.png')
insert into furniture (brand_id,category_id,furniture_name,real_height,real_width,pixel_height,pixel_width,resolution,click_rate,file_path,file_name)
VALUES (3,null,'bench_r_22x69_ziggy',22,69,88,276,72,0,'./public/app/Media/furniture_objects/','bench_r_22x69_ziggy.png')
insert into furniture (brand_id,category_id,furniture_name,real_height,real_width,pixel_height,pixel_width,resolution,click_rate,file_path,file_name)
VALUES (3,null,'bench_s_22x20_ziggy',22,20,88,80,72,0,'./public/app/Media/furniture_objects/','bench_s_22x20_ziggy.png')
insert into furniture (brand_id,category_id,furniture_name,real_height,real_width,pixel_height,pixel_width,resolution,click_rate,file_path,file_name)
VALUES (3,null,'chair_f_29x25_emil',29,25,116,100,72,0,'./public/app/Media/furniture_objects/','chair_f_29x25_emil.png')
insert into furniture (brand_id,category_id,furniture_name,real_height,real_width,pixel_height,pixel_width,resolution,click_rate,file_path,file_name)
VALUES (3,null,'chair_f_30x28',30,28,120,112,72,0,'./public/app/Media/furniture_objects/','chair_f_30x28.png')
insert into furniture (brand_id,category_id,furniture_name,real_height,real_width,pixel_height,pixel_width,resolution,click_rate,file_path,file_name)
VALUES (3,null,'chair_f_32x26_aluna',32,26,128,104,72,0,'./public/app/Media/furniture_objects/','chair_f_32x26_aluna.png')
insert into furniture (brand_id,category_id,furniture_name,real_height,real_width,pixel_height,pixel_width,resolution,click_rate,file_path,file_name)
VALUES (3,null,'chair_f_32x27_nook',32,27,128,108,72,0,'./public/app/Media/furniture_objects/','chair_f_32x27_nook.png')
insert into furniture (brand_id,category_id,furniture_name,real_height,real_width,pixel_height,pixel_width,resolution,click_rate,file_path,file_name)
VALUES (3,null,'chair_f_34x17_crestwood',34,17,136,68,72,0,'./public/app/Media/furniture_objects/','chair_f_34x17_crestwood.png')
insert into furniture (brand_id,category_id,furniture_name,real_height,real_width,pixel_height,pixel_width,resolution,click_rate,file_path,file_name)
VALUES (3,null,'chair_f_34x19_porter',34,19,136,76,72,0,'./public/app/Media/furniture_objects/','chair_f_34x19_porter.png')
insert into furniture (brand_id,category_id,furniture_name,real_height,real_width,pixel_height,pixel_width,resolution,click_rate,file_path,file_name)
VALUES (3,null,'chair_f_34x29_grace',34,29,136,116,72,0,'./public/app/Media/furniture_objects/','chair_f_34x29_grace.png')
insert into furniture (brand_id,category_id,furniture_name,real_height,real_width,pixel_height,pixel_width,resolution,click_rate,file_path,file_name)
VALUES (3,null,'chair_f_35x37_rowan',35,37,140,148,72,0,'./public/app/Media/furniture_objects/','chair_f_35x37_rowan.png')
insert into furniture (brand_id,category_id,furniture_name,real_height,real_width,pixel_height,pixel_width,resolution,click_rate,file_path,file_name)
VALUES (3,null,'chair_f_36x38',36,38,144,152,72,0,'./public/app/Media/furniture_objects/','chair_f_36x38.png')
insert into furniture (brand_id,category_id,furniture_name,real_height,real_width,pixel_height,pixel_width,resolution,click_rate,file_path,file_name)
VALUES (3,null,'chair_f_37x38_dean',37,38,148,152,72,0,'./public/app/Media/furniture_objects/','chair_f_37x38_dean.png')
insert into furniture (brand_id,category_id,furniture_name,real_height,real_width,pixel_height,pixel_width,resolution,click_rate,file_path,file_name)
VALUES (3,null,'chair_f_38x34_atlanta',38,34,152,136,72,0,'./public/app/Media/furniture_objects/','chair_f_38x34_atlanta.png')
insert into furniture (brand_id,category_id,furniture_name,real_height,real_width,pixel_height,pixel_width,resolution,click_rate,file_path,file_name)
VALUES (3,null,'chair_f_40x33',40,33,160,132,72,0,'./public/app/Media/furniture_objects/','chair_f_40x33.png')
insert into furniture (brand_id,category_id,furniture_name,real_height,real_width,pixel_height,pixel_width,resolution,click_rate,file_path,file_name)
VALUES (3,null,'chair_f_43x24_hayden',43,24,172,96,72,0,'./public/app/Media/furniture_objects/','chair_f_43x24_hayden.png')
insert into furniture (brand_id,category_id,furniture_name,real_height,real_width,pixel_height,pixel_width,resolution,click_rate,file_path,file_name)
VALUES (3,null,'chair_r_29x35',29,35,116,140,72,0,'./public/app/Media/furniture_objects/','chair_r_29x35.png')
insert into furniture (brand_id,category_id,furniture_name,real_height,real_width,pixel_height,pixel_width,resolution,click_rate,file_path,file_name)
VALUES (3,null,'chair_r_30x31',30,31,120,124,72,0,'./public/app/Media/furniture_objects/','chair_r_30x31.png')
insert into furniture (brand_id,category_id,furniture_name,real_height,real_width,pixel_height,pixel_width,resolution,click_rate,file_path,file_name)
VALUES (3,null,'chair_r_32x27_nook',32,27,128,108,72,0,'./public/app/Media/furniture_objects/','chair_r_32x27_nook.png')
insert into furniture (brand_id,category_id,furniture_name,real_height,real_width,pixel_height,pixel_width,resolution,click_rate,file_path,file_name)
VALUES (3,null,'chair_r_34x20_crestwood',34,20,136,80,72,0,'./public/app/Media/furniture_objects/','chair_r_34x20_crestwood.png')
insert into furniture (brand_id,category_id,furniture_name,real_height,real_width,pixel_height,pixel_width,resolution,click_rate,file_path,file_name)
VALUES (3,null,'chair_r_34x24_porter',34,24,136,96,72,0,'./public/app/Media/furniture_objects/','chair_r_34x24_porter.png')
insert into furniture (brand_id,category_id,furniture_name,real_height,real_width,pixel_height,pixel_width,resolution,click_rate,file_path,file_name)
VALUES (3,null,'chair_r_34x34_grace',34,34,136,136,72,0,'./public/app/Media/furniture_objects/','chair_r_34x34_grace.png')
insert into furniture (brand_id,category_id,furniture_name,real_height,real_width,pixel_height,pixel_width,resolution,click_rate,file_path,file_name)
VALUES (3,null,'chair_r_37x38_dean',37,38,148,152,72,0,'./public/app/Media/furniture_objects/','chair_r_37x38_dean.png')
insert into furniture (brand_id,category_id,furniture_name,real_height,real_width,pixel_height,pixel_width,resolution,click_rate,file_path,file_name)
VALUES (3,null,'chair_r_38x40_atlanta',38,40,152,160,72,0,'./public/app/Media/furniture_objects/','chair_r_38x40_atlanta.png')
insert into furniture (brand_id,category_id,furniture_name,real_height,real_width,pixel_height,pixel_width,resolution,click_rate,file_path,file_name)
VALUES (3,null,'chair_r_40x33',40,33,160,132,72,0,'./public/app/Media/furniture_objects/','chair_r_40x33.png')
insert into furniture (brand_id,category_id,furniture_name,real_height,real_width,pixel_height,pixel_width,resolution,click_rate,file_path,file_name)
VALUES (3,null,'chair_r_43x28_hayden',43,28,172,112,72,0,'./public/app/Media/furniture_objects/','chair_r_43x28_hayden.png')
insert into furniture (brand_id,category_id,furniture_name,real_height,real_width,pixel_height,pixel_width,resolution,click_rate,file_path,file_name)
VALUES (3,null,'chair_s_29x35',29,35,116,140,72,0,'./public/app/Media/furniture_objects/','chair_s_29x35.png')
insert into furniture (brand_id,category_id,furniture_name,real_height,real_width,pixel_height,pixel_width,resolution,click_rate,file_path,file_name)
VALUES (3,null,'chair_s_30x31',30,31,120,124,72,0,'./public/app/Media/furniture_objects/','chair_s_30x31.png')
insert into furniture (brand_id,category_id,furniture_name,real_height,real_width,pixel_height,pixel_width,resolution,click_rate,file_path,file_name)
VALUES (3,null,'chair_s_34x20_crestwood',34,20,136,80,72,0,'./public/app/Media/furniture_objects/','chair_s_34x20_crestwood.png')
insert into furniture (brand_id,category_id,furniture_name,real_height,real_width,pixel_height,pixel_width,resolution,click_rate,file_path,file_name)
VALUES (3,null,'chair_s_34x34_grace',34,34,136,136,72,0,'./public/app/Media/furniture_objects/','chair_s_34x34_grace.png')
insert into furniture (brand_id,category_id,furniture_name,real_height,real_width,pixel_height,pixel_width,resolution,click_rate,file_path,file_name)
VALUES (3,null,'chair_s_37x37_dean',37,37,148,148,72,0,'./public/app/Media/furniture_objects/','chair_s_37x37_dean.png')
insert into furniture (brand_id,category_id,furniture_name,real_height,real_width,pixel_height,pixel_width,resolution,click_rate,file_path,file_name)
VALUES (3,null,'chair_s_38x40_atlanta',38,40,152,160,72,0,'./public/app/Media/furniture_objects/','chair_s_38x40_atlanta.png')
insert into furniture (brand_id,category_id,furniture_name,real_height,real_width,pixel_height,pixel_width,resolution,click_rate,file_path,file_name)
VALUES (3,null,'chair_s_43x28_hayden',43,28,172,112,72,0,'./public/app/Media/furniture_objects/','chair_s_43x28_hayden.png')
insert into furniture (brand_id,category_id,furniture_name,real_height,real_width,pixel_height,pixel_width,resolution,click_rate,file_path,file_name)
VALUES (3,null,'console_f_23x48_maggie',23,48,92,192,72,0,'./public/app/Media/furniture_objects/','console_f_23x48_maggie.png')
insert into furniture (brand_id,category_id,furniture_name,real_height,real_width,pixel_height,pixel_width,resolution,click_rate,file_path,file_name)
VALUES (3,null,'console_f_33x31_geo',33,31,132,124,72,0,'./public/app/Media/furniture_objects/','console_f_33x31_geo.png')
insert into furniture (brand_id,category_id,furniture_name,real_height,real_width,pixel_height,pixel_width,resolution,click_rate,file_path,file_name)
VALUES (3,null,'console_f_33x41_geo',33,41,132,164,72,0,'./public/app/Media/furniture_objects/','console_f_33x41_geo.png')
insert into furniture (brand_id,category_id,furniture_name,real_height,real_width,pixel_height,pixel_width,resolution,click_rate,file_path,file_name)
VALUES (3,null,'console_r_23x48_maggie',23,48,92,192,72,0,'./public/app/Media/furniture_objects/','console_r_23x48_maggie.png')
insert into furniture (brand_id,category_id,furniture_name,real_height,real_width,pixel_height,pixel_width,resolution,click_rate,file_path,file_name)
VALUES (3,null,'console_r_33x31_geo',33,31,132,124,72,0,'./public/app/Media/furniture_objects/','console_r_33x31_geo.png')
insert into furniture (brand_id,category_id,furniture_name,real_height,real_width,pixel_height,pixel_width,resolution,click_rate,file_path,file_name)
VALUES (3,null,'console_r_33x41_geo',33,41,132,164,72,0,'./public/app/Media/furniture_objects/','console_r_33x41_geo.png')
insert into furniture (brand_id,category_id,furniture_name,real_height,real_width,pixel_height,pixel_width,resolution,click_rate,file_path,file_name)
VALUES (3,null,'dresser_f_26x56_massaro',26,56,104,224,72,0,'./public/app/Media/furniture_objects/','dresser_f_26x56_massaro.png')
insert into furniture (brand_id,category_id,furniture_name,real_height,real_width,pixel_height,pixel_width,resolution,click_rate,file_path,file_name)
VALUES (3,null,'dresser_f_33x30_audrey',33,30,132,120,72,0,'./public/app/Media/furniture_objects/','dresser_f_33x30_audrey.png')
insert into furniture (brand_id,category_id,furniture_name,real_height,real_width,pixel_height,pixel_width,resolution,click_rate,file_path,file_name)
VALUES (3,null,'dresser_f_33x52_audrey',33,52,132,208,72,0,'./public/app/Media/furniture_objects/','dresser_f_33x52_audrey.png')
insert into furniture (brand_id,category_id,furniture_name,real_height,real_width,pixel_height,pixel_width,resolution,click_rate,file_path,file_name)
VALUES (3,null,'dresser_r_26x56_massaro',26,56,104,224,72,0,'./public/app/Media/furniture_objects/','dresser_r_26x56_massaro.png')
insert into furniture (brand_id,category_id,furniture_name,real_height,real_width,pixel_height,pixel_width,resolution,click_rate,file_path,file_name)
VALUES (3,null,'dresser_r_33x30_audrey',33,30,132,120,72,0,'./public/app/Media/furniture_objects/','dresser_r_33x30_audrey.png')
insert into furniture (brand_id,category_id,furniture_name,real_height,real_width,pixel_height,pixel_width,resolution,click_rate,file_path,file_name)
VALUES (3,null,'dresser_r_33x52_audrey',33,52,132,208,72,0,'./public/app/Media/furniture_objects/','dresser_r_33x52_audrey.png')
insert into furniture (brand_id,category_id,furniture_name,real_height,real_width,pixel_height,pixel_width,resolution,click_rate,file_path,file_name)
VALUES (3,null,'lamp1_f_61x17',61,17,244,68,72,0,'./public/app/Media/furniture_objects/','lamp1_f_61x17.png')
insert into furniture (brand_id,category_id,furniture_name,real_height,real_width,pixel_height,pixel_width,resolution,click_rate,file_path,file_name)
VALUES (3,null,'lamp2_f_61x17',61,17,244,68,72,0,'./public/app/Media/furniture_objects/','lamp2_f_61x17.png')
insert into furniture (brand_id,category_id,furniture_name,real_height,real_width,pixel_height,pixel_width,resolution,click_rate,file_path,file_name)
VALUES (3,null,'lamp2_f_61x19',61,19,244,76,72,0,'./public/app/Media/furniture_objects/','lamp2_f_61x19.png')
insert into furniture (brand_id,category_id,furniture_name,real_height,real_width,pixel_height,pixel_width,resolution,click_rate,file_path,file_name)
VALUES (3,null,'lamp_f_60x20',60,20,240,80,72,0,'./public/app/Media/furniture_objects/','lamp_f_60x20.png')
insert into furniture (brand_id,category_id,furniture_name,real_height,real_width,pixel_height,pixel_width,resolution,click_rate,file_path,file_name)
VALUES (3,null,'lamp_f_68x10',68,10,272,40,72,0,'./public/app/Media/furniture_objects/','lamp_f_68x10.png')
insert into furniture (brand_id,category_id,furniture_name,real_height,real_width,pixel_height,pixel_width,resolution,click_rate,file_path,file_name)
VALUES (3,null,'lamp_f_77x15',77,15,308,60,72,0,'./public/app/Media/furniture_objects/','lamp_f_77x15.png')
insert into furniture (brand_id,category_id,furniture_name,real_height,real_width,pixel_height,pixel_width,resolution,click_rate,file_path,file_name)
VALUES (3,null,'nightstand_f_18x24_massaro',18,24,72,96,72,0,'./public/app/Media/furniture_objects/','nightstand_f_18x24_massaro.png')
insert into furniture (brand_id,category_id,furniture_name,real_height,real_width,pixel_height,pixel_width,resolution,click_rate,file_path,file_name)
VALUES (3,null,'nightstand_f_24x18_acorn',24,18,96,72,72,0,'./public/app/Media/furniture_objects/','nightstand_f_24x18_acorn.png')
insert into furniture (brand_id,category_id,furniture_name,real_height,real_width,pixel_height,pixel_width,resolution,click_rate,file_path,file_name)
VALUES (3,null,'nightstand_f_26x21_audrey',26,21,104,84,72,0,'./public/app/Media/furniture_objects/','nightstand_f_26x21_audrey.png')
insert into furniture (brand_id,category_id,furniture_name,real_height,real_width,pixel_height,pixel_width,resolution,click_rate,file_path,file_name)
VALUES (3,null,'nightstand_r_18x24_massaro',18,24,72,96,72,0,'./public/app/Media/furniture_objects/','nightstand_r_18x24_massaro.png')
insert into furniture (brand_id,category_id,furniture_name,real_height,real_width,pixel_height,pixel_width,resolution,click_rate,file_path,file_name)
VALUES (3,null,'nightstand_r_24x18_acorn',24,18,96,72,72,0,'./public/app/Media/furniture_objects/','nightstand_r_24x18_acorn.png')
insert into furniture (brand_id,category_id,furniture_name,real_height,real_width,pixel_height,pixel_width,resolution,click_rate,file_path,file_name)
VALUES (3,null,'nightstand_r_26x21_audrey',26,21,104,84,72,0,'./public/app/Media/furniture_objects/','nightstand_r_26x21_audrey.png')
insert into furniture (brand_id,category_id,furniture_name,real_height,real_width,pixel_height,pixel_width,resolution,click_rate,file_path,file_name)
VALUES (3,null,'sectional_f_35x107_henry',35,107,140,428,72,0,'./public/app/Media/furniture_objects/','sectional_f_35x107_henry.png')
insert into furniture (brand_id,category_id,furniture_name,real_height,real_width,pixel_height,pixel_width,resolution,click_rate,file_path,file_name)
VALUES (3,null,'sectional_r_35x107_henry',35,107,140,428,72,0,'./public/app/Media/furniture_objects/','sectional_r_35x107_henry.png')
insert into furniture (brand_id,category_id,furniture_name,real_height,real_width,pixel_height,pixel_width,resolution,click_rate,file_path,file_name)
VALUES (3,null,'sofa_f_31x85_urban',31,85,124,340,72,0,'./public/app/Media/furniture_objects/','sofa_f_31x85_urban.png')
insert into furniture (brand_id,category_id,furniture_name,real_height,real_width,pixel_height,pixel_width,resolution,click_rate,file_path,file_name)
VALUES (3,null,'sofa_f_32x66_mathias',32,66,128,264,72,0,'./public/app/Media/furniture_objects/','sofa_f_32x66_mathias.png')
insert into furniture (brand_id,category_id,furniture_name,real_height,real_width,pixel_height,pixel_width,resolution,click_rate,file_path,file_name)
VALUES (3,null,'sofa_f_35x73_paidge copy',35,73,140,292,72,0,'./public/app/Media/furniture_objects/','sofa_f_35x73_paidge copy.png')
insert into furniture (brand_id,category_id,furniture_name,real_height,real_width,pixel_height,pixel_width,resolution,click_rate,file_path,file_name)
VALUES (3,null,'sofa_f_35x73_paidge',35,73,140,292,72,0,'./public/app/Media/furniture_objects/','sofa_f_35x73_paidge.png')
insert into furniture (brand_id,category_id,furniture_name,real_height,real_width,pixel_height,pixel_width,resolution,click_rate,file_path,file_name)
VALUES (3,null,'sofa_f_35x73_red',35,73,140,292,72,0,'./public/app/Media/furniture_objects/','sofa_f_35x73_red.png')
insert into furniture (brand_id,category_id,furniture_name,real_height,real_width,pixel_height,pixel_width,resolution,click_rate,file_path,file_name)
VALUES (3,null,'sofa_r_31x85_urban',31,85,124,340,72,0,'./public/app/Media/furniture_objects/','sofa_r_31x85_urban.png')
insert into furniture (brand_id,category_id,furniture_name,real_height,real_width,pixel_height,pixel_width,resolution,click_rate,file_path,file_name)
VALUES (3,null,'sofa_r_32x66_mathias',32,66,128,264,72,0,'./public/app/Media/furniture_objects/','sofa_r_32x66_mathias.png')
insert into furniture (brand_id,category_id,furniture_name,real_height,real_width,pixel_height,pixel_width,resolution,click_rate,file_path,file_name)
VALUES (3,null,'sofa_r_35x73_paidge',35,73,140,292,72,0,'./public/app/Media/furniture_objects/','sofa_r_35x73_paidge.png')
insert into furniture (brand_id,category_id,furniture_name,real_height,real_width,pixel_height,pixel_width,resolution,click_rate,file_path,file_name)
VALUES (3,null,'sofa_s_32x39_mathias',32,39,128,156,72,0,'./public/app/Media/furniture_objects/','sofa_s_32x39_mathias.png')
insert into furniture (brand_id,category_id,furniture_name,real_height,real_width,pixel_height,pixel_width,resolution,click_rate,file_path,file_name)
VALUES (3,null,'sofa_s_35x38_paidge',35,38,140,152,72,0,'./public/app/Media/furniture_objects/','sofa_s_35x38_paidge.png')
insert into furniture (brand_id,category_id,furniture_name,real_height,real_width,pixel_height,pixel_width,resolution,click_rate,file_path,file_name)
VALUES (3,null,'stool_b_41x21_saddle',41,21,164,84,72,0,'./public/app/Media/furniture_objects/','stool_b_41x21_saddle.png')
insert into furniture (brand_id,category_id,furniture_name,real_height,real_width,pixel_height,pixel_width,resolution,click_rate,file_path,file_name)
VALUES (3,null,'stool_f_41x21_saddle',41,21,164,84,72,0,'./public/app/Media/furniture_objects/','stool_f_41x21_saddle.png')
insert into furniture (brand_id,category_id,furniture_name,real_height,real_width,pixel_height,pixel_width,resolution,click_rate,file_path,file_name)
VALUES (3,null,'stool_s_41x21_saddle',41,21,164,84,72,0,'./public/app/Media/furniture_objects/','stool_s_41x21_saddle.png')
insert into furniture (brand_id,category_id,furniture_name,real_height,real_width,pixel_height,pixel_width,resolution,click_rate,file_path,file_name)
VALUES (3,null,'studio_455_mirror_36x56',mirror,undefined,NaN,NaN,72,0,'./public/app/Media/furniture_objects/','studio_455_mirror_36x56.png')
insert into furniture (brand_id,category_id,furniture_name,real_height,real_width,pixel_height,pixel_width,resolution,click_rate,file_path,file_name)
VALUES (3,null,'table_f_16x19_gem',16,19,64,76,72,0,'./public/app/Media/furniture_objects/','table_f_16x19_gem.png')
insert into furniture (brand_id,category_id,furniture_name,real_height,real_width,pixel_height,pixel_width,resolution,click_rate,file_path,file_name)
VALUES (3,null,'table_f_17x15_martini',17,15,68,60,72,0,'./public/app/Media/furniture_objects/','table_f_17x15_martini.png')
insert into furniture (brand_id,category_id,furniture_name,real_height,real_width,pixel_height,pixel_width,resolution,click_rate,file_path,file_name)
VALUES (3,null,'table_f_17x58_reeve',17,58,68,232,72,0,'./public/app/Media/furniture_objects/','table_f_17x58_reeve.png')
insert into furniture (brand_id,category_id,furniture_name,real_height,real_width,pixel_height,pixel_width,resolution,click_rate,file_path,file_name)
VALUES (3,null,'table_f_18x16_hex',18,16,72,64,72,0,'./public/app/Media/furniture_objects/','table_f_18x16_hex.png')
insert into furniture (brand_id,category_id,furniture_name,real_height,real_width,pixel_height,pixel_width,resolution,click_rate,file_path,file_name)
VALUES (3,null,'table_f_18x21',18,21,72,84,72,0,'./public/app/Media/furniture_objects/','table_f_18x21.png')
insert into furniture (brand_id,category_id,furniture_name,real_height,real_width,pixel_height,pixel_width,resolution,click_rate,file_path,file_name)
VALUES (3,null,'table_f_19x40_studio1904',19,40,76,160,72,0,'./public/app/Media/furniture_objects/','table_f_19x40_studio1904.png')
insert into furniture (brand_id,category_id,furniture_name,real_height,real_width,pixel_height,pixel_width,resolution,click_rate,file_path,file_name)
VALUES (3,null,'table_f_19x41',19,41,76,164,72,0,'./public/app/Media/furniture_objects/','table_f_19x41.png')
insert into furniture (brand_id,category_id,furniture_name,real_height,real_width,pixel_height,pixel_width,resolution,click_rate,file_path,file_name)
VALUES (3,null,'table_f_20x52',20,52,80,208,72,0,'./public/app/Media/furniture_objects/','table_f_20x52.png')
insert into furniture (brand_id,category_id,furniture_name,real_height,real_width,pixel_height,pixel_width,resolution,click_rate,file_path,file_name)
VALUES (3,null,'table_f_22x24_reclaimed',22,24,88,96,72,0,'./public/app/Media/furniture_objects/','table_f_22x24_reclaimed.png')
insert into furniture (brand_id,category_id,furniture_name,real_height,real_width,pixel_height,pixel_width,resolution,click_rate,file_path,file_name)
VALUES (3,null,'table_f_26x21_geo',26,21,104,84,72,0,'./public/app/Media/furniture_objects/','table_f_26x21_geo.png')
insert into furniture (brand_id,category_id,furniture_name,real_height,real_width,pixel_height,pixel_width,resolution,click_rate,file_path,file_name)
VALUES (3,null,'table_f_30x50_modern',30,50,120,200,72,0,'./public/app/Media/furniture_objects/','table_f_30x50_modern.png')
insert into furniture (brand_id,category_id,furniture_name,real_height,real_width,pixel_height,pixel_width,resolution,click_rate,file_path,file_name)
VALUES (3,null,'table_f_30x60_uptown',30,60,120,240,72,0,'./public/app/Media/furniture_objects/','table_f_30x60_uptown.png')
insert into furniture (brand_id,category_id,furniture_name,real_height,real_width,pixel_height,pixel_width,resolution,click_rate,file_path,file_name)
VALUES (3,null,'table_f_30x68_adelaide',30,68,120,272,72,0,'./public/app/Media/furniture_objects/','table_f_30x68_adelaide.png')
insert into furniture (brand_id,category_id,furniture_name,real_height,real_width,pixel_height,pixel_width,resolution,click_rate,file_path,file_name)
VALUES (3,null,'table_f_30x84_westwood',30,84,120,336,72,0,'./public/app/Media/furniture_objects/','table_f_30x84_westwood.png')
insert into furniture (brand_id,category_id,furniture_name,real_height,real_width,pixel_height,pixel_width,resolution,click_rate,file_path,file_name)
VALUES (3,null,'table_f_36x48_counter',36,48,144,192,72,0,'./public/app/Media/furniture_objects/','table_f_36x48_counter.png')
insert into furniture (brand_id,category_id,furniture_name,real_height,real_width,pixel_height,pixel_width,resolution,click_rate,file_path,file_name)
VALUES (3,null,'table_r_26x24_geo',26,24,104,96,72,0,'./public/app/Media/furniture_objects/','table_r_26x24_geo.png')
insert into furniture (brand_id,category_id,furniture_name,real_height,real_width,pixel_height,pixel_width,resolution,click_rate,file_path,file_name)
VALUES (3,null,'table_r_30x50_modern',30,50,120,200,72,0,'./public/app/Media/furniture_objects/','table_r_30x50_modern.png')
insert into furniture (brand_id,category_id,furniture_name,real_height,real_width,pixel_height,pixel_width,resolution,click_rate,file_path,file_name)
VALUES (3,null,'table_r_30x60_parsons',30,60,120,240,72,0,'./public/app/Media/furniture_objects/','table_r_30x60_parsons.png')
insert into furniture (brand_id,category_id,furniture_name,real_height,real_width,pixel_height,pixel_width,resolution,click_rate,file_path,file_name)
VALUES (3,null,'table_r_36x48_counter',36,48,144,192,72,0,'./public/app/Media/furniture_objects/','table_r_36x48_counter.png')
